name: Deploy para AWS Lambda via Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build e Deploy da Imagem para a Lambda
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar credenciais da AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login no Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Definir variáveis
        id: vars
        run: |
          IMAGE_TAG=latest
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          echo "ACCOUNT_ID=$ACCOUNT_ID" >> $GITHUB_ENV
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          echo "ECR_URI=$ACCOUNT_ID.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}" >> $GITHUB_ENV

      - name: Build da imagem Docker
        run: |
          docker build -t $ECR_URI:$IMAGE_TAG .

      - name: Push da imagem para o ECR
        run: |
          docker push $ECR_URI:$IMAGE_TAG

      - name: Atualizar a função Lambda
        run: |
          aws lambda update-function-code \
            --function-name radar-lambda \
            --image-uri $ECR_URI:$IMAGE_TAG
